encryption:
  env_key_name: ENCRYPTION_KEY
  key_file: cache/.encryption_key
  use_env_key: true
github_api:
  encrypted: false
  token: ''
instagram:
  encrypted: true
  password: ''
  username: gAAAAABphfgfGfO7oqRNuI-8bpdKdOUD7z32iL7DviEKC3xPRAHPvb3i0b4YU4FrWDqH5gYgrYgAoVKkiI9-ZNykm1r2pkbxhA==
test_platform:
  encrypted: true
  test_field: gAAAAABphfiugy2AN4l46f2JJs4y9LD11iLONgwcB3jDyyukzWBy07je2gnc8OtcjdduxXCriyIvmhjaJXhBhYasjKDGIl4gNXhRrJR7y6lJ1W7X0jGmeEA=
tiktok:
  encrypted: false
  password: ''
  username: ''
youtube:
  email: ''
  encrypted: false
  password: ''
