encryption:
  env_key_name: ENCRYPTION_KEY
  key_file: cache/.encryption_key
  use_env_key: true
github_api:
  encrypted: false
  token: ''
instagram:
  encrypted: true
  password: ''
  username: gAAAAABphfgfGfO7oqRNuI-8bpdKdOUD7z32iL7DviEKC3xPRAHPvb3i0b4YU4FrWDqH5gYgrYgAoVKkiI9-ZNykm1r2pkbxhA==
test_platform:
  encrypted: true
  test_field: gAAAAABphfgTJatd2AJd2LWKFLD973YYluM7y0rX2Ed14heS8JS4C8I8OdDJKeZ7hR5FRvrlEwsvtln_7kf4JTLz1B_qF1dNv4Kf-DO_ZNSKqS6y08ePC4Y=
tiktok:
  encrypted: false
  password: ''
  username: ''
youtube:
  email: ''
  encrypted: false
  password: ''
